url: "http://spivey.world" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
excerpt_separator   : "\n"
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true